flowchart LR

BANK["银行"]

WECHAT["微信支付"]
ALIPAY["支付宝"]

WISE["Wise"]
N26["N26"]
IFAST["iFast"]

CEX["加密货币交易所"]

USDT["USDT"]
USDC["USDC"]

UCARD["U卡"]

VISA["Visa"]
MC["Mastercard"]

APPLE["Apple Pay"]

MERCHANT["全球商户"]


BANK --> WECHAT
BANK --> ALIPAY

BANK --> WISE
BANK --> N26
BANK --> IFAST

WISE --> CEX
N26 --> CEX
IFAST --> CEX

CEX --> USDT
CEX --> USDC

USDT --> UCARD
USDC --> UCARD

UCARD --> VISA
UCARD --> MC

VISA --> APPLE
MC --> APPLE

WECHAT --> MERCHANT
ALIPAY --> MERCHANT

VISA --> MERCHANT
MC --> MERCHANT

APPLE --> MERCHANT
